/*
 * Movie Actions
 */
export const SEARCH_MOVIES = 'SEARCH_MOVIES'
export const SET_SEARCH_MOVIE_TEXT = 'SET_SEARCH_MOVIE_TEXT'
export const SET_SEARCH_MOVIE_SEARCH_BY = 'SET_SEARCH_MOVIE_SEARCH_BY'
export const SET_SEARCH_MOVIE_SORT_BY = 'SET_SEARCH_MOVIE_SORT_BY'
export const FETCH_MOVIES = 'FETCH_MOVIES'
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'
